### PR TITLE
add ClassDefItem$get_annotations()

### PR DESCRIPTION
**Pull request by jinsooyoon-kr**
add get_annotations method in ClassDefItem.

return value is list of AnnotationItem, return [] if annotation is not exist.

### CODE REVIEW

**Comment by decinc** [comment]
Collecting lxml (from androguard==3.4.0)

  Downloading https://files.pythonhosted.org/packages/e1/f5/5eb3b491958dcfdcfa5daae3c655ab59276bc216ca015e44743c9c220e9e/lxml-4.4.0.tar.gz (4.5MB)

    Complete output from command python setup.py egg_info:

    This lxml version requires Python 2.7, 3.5 or later.


error log looks like environment problem on python 3.4

**Comment by reox** [comment]
Okay, then disable tests for 3.4 - these versions are hardly used anyways.
Just comment it out in .travis.yml

**Comment by decinc** [comment]
I would write test code for get_annotation() because of codecov fails.
just create new file named testAnnotation.py and write some test code?

or edit test_dex.py?

**Comment by reox** [comment]
i guess you can create a new file test_annotations.py in the tests folder.
We could still merge them lateron if there is a problem :)

**Comment by reox** [comment]
nice! So is this ready to merge?

**Comment by decinc** [comment]
yep. ready to merge

**Comment by reox** [comment]
thanks for the PR!

**Pull request merged**
