### PR TITLE
Switch to C implementation of mutf8 decoder

### PR DESCRIPTION
**Pull request by TkTech**
This is wildly incomplete, I'm experimenting and seeing if there's interest in finishing this. This uses my https://github.com/TkTech/mutf8 encoder/decoder to speed things up.

On the 41Mb Facebook.apk (v294.0.0.39.118), this takes the time for:

```
from androguard.misc import AnalyzeAPK
a, d, dx = AnalyzeAPK("Facebook.apk")
```

... from an average of 16 seconds down to an average of 12, a 25% improvement while _removing_ the `MUTF8String` proxy. Peek memory usage increased slightly, but this is because now-unnecessary copies are being kept around and this can be eliminated if there's interest in finishing this.

Note that I've only finished enough to make sure AnalyzeAPK can run.

Benchmark timing for `decode()`:

```
------------------------------------------------------------------------------------------------- benchmark 'MUTF-8 Decoding': 3 tests ------------------------------------------------------------------------------------------------
Name (time in ns)                                    Min                     Max                  Mean                StdDev                Median                 IQR             Outliers  OPS (Kops/s)            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_decode[cmutf8-decode_modified_utf8]        100.9999 (1.0)        1,439.9999 (1.0)        109.6700 (1.0)         32.2136 (1.0)        102.0000 (1.0)        0.5000 (1.0)      3800;5924    9,118.2638 (1.0)       48544         200
test_decode[pymutf8-decode_modified_utf8]     1,199.9800 (11.88)     52,399.9915 (36.39)    1,458.6200 (13.30)    1,348.9298 (41.87)    1,300.0099 (12.75)     99.9717 (199.94)     186;400      685.5795 (0.08)       9971           1
test_decode[androguard_mutf8-decode]          1,799.9846 (17.82)    115,700.0079 (80.35)    2,086.1480 (19.02)    1,520.4937 (47.20)    1,899.9854 (18.63)    100.0008 (200.00)   3990;9380      479.3524 (0.05)     112360           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by reox** [comment]
nice! My try with the mutf8 parsing was a bit quick'n'dirty. Ping me if you want it merged!

**Comment by subho007** [comment]
Hello @TkTech please let me know if we can go ahead and use this? I have tested this branch and it works beautifully. Happy to take the load of mutf8 parsing to another library (esp. if it is a C library with faster performance improvement) than maintaining it in Androguard itself.

**Comment by TkTech** [comment]
I spent some time on this today, there are a few test failures to fix still.

**Comment by totoag** [comment]
Is it still in progress and valuable ?

**Comment by TkTech** [comment]
Yes, definitely still useful for the performance boost and correct string decoding. I just don't have time to finish it.

**Comment by totoag** [comment]
@TkTech I can do it but what is not finish ? The mutf8 on your side or the PR for Androguard ?

**Comment by TkTech** [comment]
The library is complete. The PR needs to be updated for conflicts and some tests failing need to be resolved.

**Comment by totoag** [comment]
Ok so I did that in the last commit:
https://github.com/androguard/androguard/commit/8df1fe850d21c74c4439940075ff1e9dc34274fc

Seems to work, will close this issue and open bugs if necessary

**Pull request closed without merging**
