### PR TITLE
Fixed: get_app_icon().

### PR DESCRIPTION
**Pull request by feicong**
get_app_icon() maybe returns xml file,  not a png file.

### CODE REVIEW

**Comment by reox** [comment]
thanks for the PR! Do you have some samples that show this behaviour? maybe there is something else wrong.

**Comment by feicong** [comment]
yes, it's an adaptive-icon. the xml file contents like this:

```
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon
  xmlns:android="http://schemas.android.com/apk/res/android">
    <background>
        <bitmap android:src="@mipmap/adaptiveproduct_google_plus_background_color_108" />
    </background>
    <foreground>
        <bitmap android:src="@mipmap/adaptiveproduct_google_plus_foreground_color_108" />
    </foreground>
</adaptive-icon>
```

when analyzing apk, I usually only want to get the PNG file path with the maximum resolution. If it is adaptive-icon, I need to generate the icon dynamically, which is more difficult to deal with.

here is the test file:

[update.apk.zip](https://github.com/androguard/androguard/files/1886946/update.apk.zip)

**Comment by subho007** [comment]
If the type is XML, one should read the XML and re-call the function to find the icon path.

**Comment by reox** [comment]
that might be very complicated. The background and foreground can be given as some kind of vector file (again an XML).
I think the best solution would be to check in the get_app_icon if a XML is returned, then change the max_dpi to 0xFFFE - 1 (ANY_DPI -1), so you _should_ get an actual icon. The only problem could be apps that are build only for v26. Then there might be no icon file.

**Comment by feicong** [comment]
maybe the best solution is set an argument to the get_app_icon function.

**Comment by subho007** [comment]
what do you think about this @reox ?

**Comment by reox** [comment]
My thoughts on this: Levae the get_app_icon function as it is, as it does the correct thing...
If you really want a png file, then just check it on your own and call get_app_icon with a lower DPI using dpi = 0xFFFE - 1.

There are probably at some day APKs which have only an XML file and no PNG at all. So patching the function to ignore xml at all is probably not so good.

**Pull request closed without merging**
