### PR TITLE
Restore 'androguard cg' callgraph generation

### PR DESCRIPTION
**Pull request by ehrenb**
- Readded several dependencies, such as networkx, matplotlib, pyyaml, and pyqt5 to generate and render callgraphs
- Readded previous get_call_graph() function and made a few fixes
- fixed some docstring inaccuracies with MethodAnalysis xref_from/to
- Can export callgraphs to gml, gexf, graphml, and net (pajek), **but not gpickel or yaml because there are embedded attributes that are not serializable in EncodedMethod objects (BufferedReader in EncodedMethod.buff)**. 

Tested with the following commands:

```bash
androguard --verbose cg --show --classname "Ltests/androguard/*" ~/projects/androguard/tests/data/APK/TestActivity.apk
```

ex1

```bash
androguard --verbose cg --show --methodname "Test*" ~/projects/androguard/tests/data/APK/TestActivity.apk
```

ex2

```bash
androguard --verbose cg --show --descriptor '\(LTestDefaultPackage;\sI\sI\sLTestDefaultPackage\$TestInnerClass;\)V' ~/projects/androguard/tests/data/APK/TestActivity.apk
```

ex3

### CODE REVIEW

**Comment by erev0s** [comment]
@ehrenb thank you very much for this!!
Could you also please generate a few tests (test_callGraph.py) in the corresponding directory. I believe it is essential in making sure any future changes dont break things.

**Comment by ehrenb** [comment]
> @ehrenb thank you very much for this!!
> 
>     * There seems to be an error while installing the dependencies `Unable to find installation candidates for pyqt5-qt5 (5.15.12)`.
> 
>     * Could you also please generate a few tests (test_callGraph.py) in the corresponding directory. I believe it is essential in making sure any future changes dont break things.

Sure, I'll get

> @ehrenb thank you very much for this!!
> 
>     * There seems to be an error while installing the dependencies `Unable to find installation candidates for pyqt5-qt5 (5.15.12)`.
> 
>     * Could you also please generate a few tests (test_callGraph.py) in the corresponding directory. I believe it is essential in making sure any future changes dont break things.

Yes, I'll have this done in a couple of days hopefully.  When it's done I'll let you know here.

**Comment by erev0s** [comment]
i see also the note for installing :
~~~~
apt-get install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev
~~~~
if i am not mistaken these are required only for opening the exported formats, right?
Then, maybe i can add that info along with the examples you shared above in the wiki page (which needs to be updated anyway)

**Comment by ehrenb** [comment]
> i see also the note for installing :
> 
> ```
> apt-get install libxcb-randr0-dev libxcb-xtest0-dev libxcb-xinerama0-dev libxcb-shape0-dev libxcb-xkb-dev
> ```
> 
> if i am not mistaken these are required only for opening the exported formats, right? Then, maybe i can add that info along with the examples you shared above in the wiki page (which needs to be updated anyway)

Those dependencies were required for using the '--show' flag which uses matplotlib + qt5 to render.  I had to install them on Ubuntu 22.04, but did not test other OS's or Ubuntu versions.  Feel free to add them in where you'd like, for now I've put them in the README.

**Comment by ehrenb** [comment]
Please take another look at the latest.  The QT dependency issue was specific to Poetry, and is fixed by locking it to a specific subpackage of PyQt5 (subpackage PyQt5-Q5, which is confusing).  I also added test_callgraph.py with tests that validate number of nodes and edges in various scenarios within TestActivity.apk.

**Pull request merged**
