### PR TITLE
Fixing #363 and adding unit tests 

### PR DESCRIPTION
**Pull request by diarmaid-mcmanus**

### CODE REVIEW

**Comment by diarmaid-mcmanus** [comment]
unsure why this is failing - passes here https://travis-ci.org/diarmaid-mcmanus/androguard/builds/310505102

**Comment by reox** [comment]
The doc build failed due to a timeout... Thats weird, but maybe travis had some load issues? 46 minutes is at least twice as long as the normal runtime.

**Comment by diarmaid-mcmanus** [comment]
closing and reopening to trigger new build

**Comment by diarmaid-mcmanus** [comment]
closing and reopening to trigger new build

**Pull request merged**
