### PR TITLE
Allow multidex analysis

### LINKED ISSUE #373: Add corresponding vm to Analysis object for ClassAnalysis
Currently a very hackish way is implemented at https://github.com/androguard/androguard/blob/master/androguard/session.py which breaks Xrefs from different dex files in multi-dex.

The idea is to create a reference of `vm` in `ClassAnalysis` at
- https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L762-L775
- https://github.com/androguard/androguard/blob/master/androguard/core/analysis/analysis.py#L649

Single `Analysis` object should contain the analysis across all the dex file, and on getting an `xref` it should also have a reference of the `vm` object which it is related to.

@reox thoughts ?

### PR DESCRIPTION
**Pull request by subho007**
Following are the changes:

1. Instead of using the `last_vm` get the `vm` dynamically via ClassManager
2. do the analysis on all the `vm` present in `self.vms`
3. Refactor `session.py` to support multidex analysis

@reox @adesnos can you please review the changes ? I'll write testcases in different PR

fixes #373 #359

### CODE REVIEW

**Comment by reox** [comment]
looks like travis is handling large outputs as error... thus the default logging should probably not be debug on travis?

**Comment by reox** [comment]
Oh, I see: the logs are only displayed if there is an actuall error:
```
ERROR: testArrays (test_decompiler.DecompilerTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/androguard/androguard/tests/test_decompiler.py", line 23, in testArrays

    self.assertIn("{20, 30, 40, 50};", z.get_source())

  File "/home/travis/build/androguard/androguard/androguard/core/bytecodes/dvm.py", line 3688, in get_source

    return self.CM.decompiler_ob.get_source_class(self)

nose.proxy.AttributeError: 'NoneType' object has no attribute 'get_source_class'
```

**Comment by subho007** [comment]
Ahh, fix is on the way.

**Comment by subho007** [comment]
@reox fixed the errors. Following are the fixes:

1. Decompiler test was failing. This was fixed by `d.set_vmanalysis(dx)` because `decompiler_ob` needs `dx`

2. made `session` backward compatible to pass the tests.

Please review 👍

**Comment by subho007** [comment]
@reox can you review this ?

**Pull request merged**
