### PR TITLE
Readable Readme for Androguard

### PR DESCRIPTION
**Pull request by subho007**
Guys, I wanted to cleanup the readme.txt to a clear Markdown format of the readme. Please don't accept the pull request yet. Some more stuffs needs to be done to make it into Androguard.

- [x] Change the Readme to Markdown
- [ ] Create a separate branch for Wiki
- [ ] Import all the Wiki documents from Google Code to Github.
- [ ] Format them all in Markdown
- [ ] Make the Wiki linkable within each other

If the changes are agreeable, please confirm so that I can send you a more completed pull request.

### CODE REVIEW

**Comment by Nikoli** [comment]
How is it going? Please move at least https://code.google.com/p/androguard/wiki/Installation to github, page in googlecode is obsolete and wrong now.

**Comment by subho007** [comment]
@Nikoli I got a bit busy, thinking of finishing it by next weekened :+1:

**Comment by adesnos** [comment]
Any update ? I will do it otherwise.

**Comment by subho007** [comment]
@adesnos I will close this issue, and do a proper one, can you give me 2 days for this ?

**Pull request closed without merging**
