### PR TITLE
added package publish automation

### PR DESCRIPTION
**Pull request by krnick**
Hi @totoag 

Good to see you back!
I notice you have updated the version of 4.0, but the PyPi didn't update it, so I added this automation for androguard
If you need any help with maintaining it, please feel free to ping me, I'd love to help maintain it together 😄 .

### CODE REVIEW

**Comment by totoag** [comment]
Yes but unfortunately I don't have access to it :( Have you ? If yes if you can add me too

**Comment by krnick** [comment]
Yeah, but I don't have PyPi permission to invite collaborators, I am only available to upload the new PyPi package, and I don't have access permission to the Androguard GitHub repository so I can't help with this automation, my PyPi permission was added by @reox, so maybe he can help with that.

Currently, I can manually upload the package, if you think this version is all set to upload, please let me know, I can help with that.

截圖 2022-07-04 下午5 44 52

**Comment by reox** [comment]
@totoag yes, I can add you! What is your pypi user name?

**Comment by reox** [comment]
@krnick I also made you an owner now, so you also should be able to invite other.

**Comment by krnick** [comment]
@reox Thanks for your kind help 😃

**Comment by totoag** [comment]
Thx awesome !! I will create an account

**Pull request merged**
