### PR TITLE
Run tests with PyPy 5.8

### PR DESCRIPTION
**Pull request by thedrow**
Since this is a pure python library I see no reason why PyPy shouldn't be supported.
Let's see if this is a no brainer.

### CODE REVIEW

**Comment by thedrow** [comment]
The failure seems legit since those classes don't have a `get_ref_off()` method.
I'm not sure how they appear on CPython.
Can anyone share their insights?

**Comment by thedrow** [comment]
I just run the tests with PyPy 5.9.0 and all tests pass.

**Comment by thedrow** [comment]
Seems like PyPy 5.9.0 is not available in Travis :(

**Comment by reox** [comment]
I tried pypy some time ago and had the same behaviour... 
Probably we should fix this bug. But I have no idea what pypy does that python don't...

**Comment by reox** [comment]
this looks really weird... there is this check:
https://github.com/androguard/androguard/blob/67b992ce0feeeb01bc69a99257916487689c3bcf/androguard/core/analysis/analysis.py#L137

And the opcodes 0x26, 0x2b, 0x2c have all the `t` format. I'm also not sure why not the other `t` types are in this function, but it might have a reason...
So I really have no idea how it is even possible that an other instruction get's into this function?!

**Comment by reox** [comment]
Is it possible that pypy < 5.9.0 has issues with interval compares?!

**Comment by reox** [comment]
see also #347 there are more pypy versions.

@thedrow have you any idea what might be wrong? The interesting thing is, that those errors should not happen. But I never used pypy - have you any experience?

**Comment by reox** [comment]
this is really weird... I tried to implement the method in the base class, but then the exception is raised. Looks like this method is actually called! (See https://travis-ci.org/androguard/androguard/jobs/306241214#L553)

**Comment by thedrow** [comment]
PyPy 5.8.0 had a bug regarding to ordering which was fixed in 5.8.1.
I recommend supporting the latest version of PyPy.

**Comment by reox** [comment]
I think this is partly not the fault of pypy... we had such bugs already where the ordering of dict keys where assumed but in fact they are not ordered.
for this other bug I'm not sure what to do. interestingly it works with some versions.

**Comment by reox** [comment]
I'll close thise one here. There are tickets describing the problem #349 and #350

**Pull request closed without merging**
