### PR TITLE
  switch pyasn1 to asn1crypto

### PR DESCRIPTION
**Pull request by shuxin**
so many bugs in pyasn1. asn1crypto is more easy in use, and no need cryptography any more.

### CODE REVIEW

**Comment by reox** [comment]
This looks really good! Is asn1crypto a drop in for cryptography, ie. do they share the same API? Then it would be totally awesome.

**Comment by shuxin** [comment]
asn1crypto is just a good parser without openssl.
verifing the signature still need openssl/cryptography/M2Crypto/...
(I have wrote a pure python version https://github.com/shuxin/apk-signature-verify, but sitll not support python3 )

**Comment by reox** [comment]
Okay I tested this now a little bit and it looks good! The only thing I can not find is valid_before and valid_after fields, see https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate.not_valid_before
Do you have any idea how to get this information?

**Comment by shuxin** [comment]
type(x509.Certificate.load(c.dump())['tbs_certificate']['validity']['not_after'].native) == datetime

**Comment by reox** [comment]
ok thanks! this is the only thing which is not so straight forward :D

**Pull request merged**
