### PR TITLE
apk: build locale code properly

### PR DESCRIPTION
**Pull request by ganadist**
Signed-off-by: Young-Ho Cha ganadist@gmail.com

### CODE REVIEW

**Comment by reox** [comment]
Is there a specific reason to concatenate the locales like this: `locale = "-r".join((language, region))`?

In my opinion the result should be `"{}_{}".format(language, region)` or if you follow the structure that is given in the documentation: `"-b+{}+{}".format(language, region)`

**Comment by ganadist** [comment]
> In my opinion the result should be "{}_{}".format(language, region)
It means "{}_r{}".format(language, region) ?

**Comment by reox** [comment]
yes, but for what is the `r`? In my opinion a locale code is for example `en_US` and not `en_rUS`?

**Comment by ganadist** [comment]
In https://developer.android.com/guide/topics/resources/providing-resources.html#table2 , describes about locale.

> The language is defined by a two-letter ISO 639-1 language code, optionally followed by a two letter ISO 3166-1-alpha-2 region code (preceded by lowercase "r").

**Comment by reox** [comment]
Ahh I see, thank you! Now I understand

**Pull request merged**
