### PR TITLE
andrototal

### PR DESCRIPTION
**Pull request by nu11p0inter**
1. andrototal.py - prints results and (automatic) upload apk/dex files to virustotal
2. andrograph.py - file's autograph - show files signatures

### CODE REVIEW

**Comment by adesnos** [comment]
Could you clean the second file ? It is a little messy.

**Comment by nu11p0inter** [comment]
Definitely. 
Which file, and where...?

**Comment by nu11p0inter** [comment]
The file is ready. clean & using androguard's code...

**Comment by nu11p0inter** [comment]
The file is ready. clean & using androguard's code...

**Comment by nu11p0inter** [comment]
Hi Antony,

I deleted the second file, using only the VT integration file.

It is not using VT-API because the API is limited for 4 requests per
minute. Since this is public code, we cannot use paid token, since it can
be easily abused by anyone.

So the parsing of the data must be manually... I performed validations so
in the case were their responses will change, it will notify the user to
request for update from Androguard.

Please let me know if you want to to add/ modify anything.

Best Regards,
Tal
http://lnkdin.me/cyber

**Pull request closed without merging**
