### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by Rafiot**
Fix https://github.com/androguard/androguard/issues/239

### CODE REVIEW

**Comment by Rafiot** [comment]
That's what I did in viper requirements file and it fixed it... Let's see.

**Comment by reox** [comment]
This one is weird... It seems that androguard is installed by pip install . - so the setup.py is executed? Maybe you need to specifiy the version for py2.7 there?

**Comment by Rafiot** [comment]
Yep, I just tried an other fix in setup.py

**Comment by Rafiot** [comment]
(okay, I'll test locally and stop pushing untested thing...)

**Comment by reox** [comment]
I think you need this patch here (last block of code) https://github.com/ipython/ipython/blob/master/README.rst#ipython-requires-python-version-3-or-above

**Comment by Rafiot** [comment]
Right, that's pretty much what I did ;)

**Comment by Rafiot** [comment]
(now fails on python 3 for an other reason)

**Comment by reox** [comment]
yes, but I think you fixed it! The py3.6 error was there before... Somehow there is now some object which can not be serialized... but this is another issue.
Thanks for looking into this!

**Comment by Rafiot** [comment]
You're welcome, I saw this issue while looking for opening an other one ;)

**Pull request merged**
